### ISSUE TITLE
Hosting an ESP webserver for logging

### ISSUE THREAD

**Issue by DhruvaG2000** [VedantParanjape/esp-wifi-logger#14]
Since this repo has wifi, I am not sure if this is the right place for requesting this...
But how feesible would it be to create an access point so that we can log the data without dependency on wifi by just connecting a phone/ laptop to the esp directly and receiving the log messages?

**Comment by VedantParanjape** [comment]
This can be done, but be adviced, it will use a lot of RAM, and it pretty much defeats the purpose of a logger
