### ISSUE TITLE
Example with webpage

### ISSUE THREAD

**Issue by rikki78** [VedantParanjape/esp-wifi-logger#6]
Thanks for attending me to this library. It is not clear to me how our if it can be used to write logs to a webpage through websockets. Can you give an example of that?

**Comment by VedantParanjape** [comment]
Currently it doesn't support, sending logs to a webpage, if i do implement, it will end up hogging lot of heap, and it doesn't make sense for a logger to have such a large memory footprint.

Even though, i have added websockets support, so using websockets you can receive logs on your PC, you just need to use websocat to do so. Check readme 

If you want to view it on browser. Run a web server on your PC which receives data from ESP32 and redirects it to the web browser.

But, websocat does a good enough job, displays color encoded logs on the terminal itself. I don't see the need for a webpage.

**Comment by rikki78** [comment]
All right thanks for your reaction. The purpose is more to show the output like normally shown on the serial port, on a webpage.

**Comment by VedantParanjape** [comment]
If you make the webserver bridge, I will be more than happy to accept a pull request.

Regards,
Vedant
