### ISSUE TITLE
ESP_LOGD and ESP_LOGV are not showing up in traces

### ISSUE THREAD

**Issue by shivam5594** [VedantParanjape/esp-wifi-logger#8]
Hi,
for this code
```
void app_main(void)
{
	start_wifi_logger();
	//while(1)
		ESP_LOGI("ESP_LOG","Looks like we connected.\n");
		ESP_LOGE("ESP_LOG","Looks like we connected.\n");
		ESP_LOGW("ESP_LOG","Looks like we connected.\n");
		ESP_LOGV("ESP_LOG","Looks like we connected.\n");
		ESP_LOGD("ESP_LOG","Looks like we connected.\n");

		wifi_log_i("wifi_log", "%s", "Looks like we connected.\n");
		wifi_log_e("wifi_log", "%s", "Looks like we connected.\n");
		wifi_log_w("wifi_log", "%s", "Looks like we connected.\n");
		wifi_log_v("wifi_log", "%s", "Looks like we connected.\n");
		wifi_log_d("wifi_log", "%s", "Looks like we connected.\n");
}
```
output I see for TCP/UDP/Websocket is 

![image](https://user-images.githubusercontent.com/26493198/98199329-c36a5c80-1edf-11eb-9616-8f1b9c143482.png)

any idea why?

**Comment by VedantParanjape** [comment]
Hi,
I assume you mean why does ESP_LOGV and ESP_LOGD not show up ?

It happens as esp_log level is set to INFO (can be set from menuconfig), so any levels below log level INFO will simply be dropped by the logger, so it won't ever get added to the queue.

![Screenshot from 2020-11-05 10-33-26](https://user-images.githubusercontent.com/22630228/98199940-6f4c9000-1f52-11eb-90d8-478a9f71ec77.png)

and to answer the part, why you see things like: "I (5619) wifi_logger: ...." and "<ba-add>idx:0 .....", this is visible as you have turned on route system logs setting, so even these functions use ESP_LOGx functions, so these calls also get added to the message queue.

Whereas all the logs using wifi_log_x() are printed as they are not sent through the esp_log, I rather generate my own log message and send it. It is recommended to use the custom defined functions and turn off route system message option, as you can see how it creates issues and if you set the log level to Debug in menuconfig, then a lot of system logs get added to the queue and queue overflows, so esp crashes every time.

**Comment by shivam5594** [comment]
Thanks for that, totally forgot about the SDKconfig file. Closing the issue.
